//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katarai.Runner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Katarai.Runner.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice - Continue on to the next test..
        /// </summary>
        public static string AboutToWriteNextTestMsg {
            get {
                return ResourceManager.GetString("AboutToWriteNextTestMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you chosen a good starting point?.
        /// </summary>
        public static string GoodStartingPointMsg {
            get {
                return ResourceManager.GetString("GoodStartingPointMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WOAH! Slow down.. you are writing code without the appropriate test in place..
        /// </summary>
        public static string ImplementationAheadMsg {
            get {
                return ResourceManager.GetString("ImplementationAheadMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you chosen the BEST next test?.
        /// </summary>
        public static string NextBestTestMsg {
            get {
                return ResourceManager.GetString("NextBestTestMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You appear to be missing {0} test{1}..
        /// </summary>
        public static string PlayerMissingTests {
            get {
                return ResourceManager.GetString("PlayerMissingTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking good - Continue on to writing the implementation..
        /// </summary>
        public static string TestingOnTrackMsg {
            get {
                return ResourceManager.GetString("TestingOnTrackMsg", resourceCulture);
            }
        }
    }
}
