@echo off
rem Needs Variables set: SOLUTION_FOLDER(eg: c:\.\source\), PACKAGES_SOURCE_FOLDER(eg: c:\.\source\Packaged), OUT_DIR (eg: bin\debug\)
SET PACKAGE_NAME=%1
SET PACKAGE_PATH=%PACKAGES_SOURCE_FOLDER%\%PACKAGE_NAME%
SET PACKAGE_DESTINATION=%~dp0

SET INTERFACE_PROJECT=Katarai.%PACKAGE_NAME%.Interfaces
SET KATADATA_PROJECT=Katarai.KataData.%PACKAGE_NAME%

SET INTERFACE_DLL=%SOLUTION_FOLDER%%KATADATA_PROJECT%\%OUT_DIR%%INTERFACE_PROJECT%.dll
SET KATADATA_DLL=%SOLUTION_FOLDER%%KATADATA_PROJECT%\%OUT_DIR%%KATADATA_PROJECT%.dll
SET ENGINE_DLL=%SOLUTION_FOLDER%%KATADATA_PROJECT%\%OUT_DIR%Engine.dll

ECHO Updating '%PACKAGE_NAME%' packaged kata dlls

XCOPY /Y "%INTERFACE_DLL%" "%PACKAGE_PATH%\MasterSolution\"
XCOPY /Y "%KATADATA_DLL%" "%PACKAGE_PATH%\MasterSolution\"

XCOPY /Y "%INTERFACE_DLL%" "%PACKAGE_PATH%\PlayerSolution\lib\"
XCOPY /Y "%ENGINE_DLL%" "%PACKAGE_PATH%\PlayerSolution\lib\"

ECHO Compressing '%PACKAGE_NAME%' packaged kata

%SOLUTION_FOLDER%..\tools\7z\7z.exe a -tzip "%PACKAGES_SOURCE_FOLDER%\%PACKAGE_NAME%.zip" "%PACKAGES_SOURCE_FOLDER%\.\%PACKAGE_NAME%\*"

ECHO Adding '%PACKAGE_NAME%' to packaged katas folder
XCOPY /Y "%PACKAGES_SOURCE_FOLDER%\%PACKAGE_NAME%.zip" "%PACKAGE_DESTINATION%"